"""N8 — LaTeX Assembler (str.replace).

Assembles the final .tex file by substituting section content into the
locked master template via pure string replacement. Gemini never touches
the template preamble — only content slots are filled.

Slots replaced (in order):
  %%SUMMARY_TEXT%%       → plain text from N7a (escaped)
  %%EXPERIENCE_BLOCK%%   → \resumeSubheading + \resumeItem from N7b
  %%PROJECTS_BLOCK%%     → \resumeProjectHeading + \resumeItem from N7c
  %%SKILLS_BLOCK%%       → \textbf{} blocks from N7d
  %%EDUCATION_BLOCK%%    → static data from config/constants
  %%CERTIFICATIONS_BLOCK%% → from kg_snapshot (if available)

Fan-in node: receives accumulated sections_output from N7a-N7d.
"""

from __future__ import annotations

import logging
import re

from server.graph.state import ResumeState
from server.services.latex_utils import escape_special_chars

_logger = logging.getLogger(__name__)

# Static education block — not generated by AI
EDUCATION_BLOCK = r"""
\resumeSubheading
  {PES College of Engineering, Mandya}{2021 -- 2023}
  {Master of Computer Applications (MCA)}{}
\resumeSubheading
  {Ramaiah Institute of Business Studies, Bangalore}{2018 -- 2021}
  {Bachelor of Computer Applications (BCA)}{}
"""


async def run(
    state: ResumeState,
    *,
    template: str,
) -> ResumeState:
    _logger.info("N8: Assembling LaTeX from %d section outputs",
                  len(state.get("sections_output", [])))

    sections: dict[str, str] = {}
    for entry in state.get("sections_output", []):
        section_name = entry.get("section", "")
        content = entry.get("content", "")
        if section_name and content:
            sections[section_name] = content

    kg = state.get("kg_snapshot", {})

    summary = _escape_plain(sections.get("summary", ""))
    experience = _escape_text_in_commands(sections.get("experience", ""))
    projects = _escape_text_in_commands(sections.get("projects", ""))
    skills = _escape_text_in_commands(sections.get("skills", ""))
    education = EDUCATION_BLOCK.strip()
    certifications = _build_certifications(kg)

    latex = template
    latex = latex.replace("%%SUMMARY_TEXT%%", summary)
    latex = latex.replace("%%EXPERIENCE_BLOCK%%", experience)
    latex = latex.replace("%%PROJECTS_BLOCK%%", projects)
    latex = latex.replace("%%SKILLS_BLOCK%%", skills)
    latex = latex.replace("%%EDUCATION_BLOCK%%", education)
    latex = latex.replace("%%CERTIFICATIONS_BLOCK%%", certifications)

    return ResumeState(
        latex_source=latex,
        latex_fix_attempts=0,
    )


def _escape_plain(text: str) -> str:
    if not text:
        return ""
    return escape_special_chars(text)


# Characters that must be escaped in LaTeX text mode
_TEXT_SPECIALS = {
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
}


def _escape_text_in_commands(text: str) -> str:
    """Escape &, %, $, #, _ in Gemini-generated LaTeX content.

    Uses a simple rules: escape special chars that aren't preceded by
    backslash. This handles mixed content (commands + plain text) by
    leaving already-correct LaTeX intact.
    """
    if not text:
        return ""
    return _safe_escape(text)


def _safe_escape(text: str) -> str:
    """Escape &, %, $, #, _ only when not preceded by backslash."""
    result = text
    for ch, esc in _TEXT_SPECIALS.items():
        # Replace ch only when not preceded by \
        result = re.sub(r"(?<!\\)" + re.escape(ch), esc, result)
    return result


def _build_certifications(kg: dict) -> str:
    certs = kg.get("certifications", [])
    if not certs:
        return ""

    lines = []
    for c in certs:
        title = c.get("title", "")
        year = c.get("year", "")
        if title:
            if year:
                lines.append(rf"\item[] \textbf{{{title}}} ({year})")
            else:
                lines.append(rf"\item[] \textbf{{{title}}}")

    return "\n      ".join(lines) if lines else ""
