"""N9 — LaTeX Validator (syntax + custom command schema validation).

Five parallel checks run against the assembled .tex file:
1. Brace balance (generic)
2. Environment matching (generic)
3. Placeholder check (generic)
4. Forbidden character check (generic)
5. Custom command schema validation (template-specific)

The CUSTOM_COMMAND_SCHEMA is hardcoded here — it must match the definitions
in template/master_resume.tex. If the template's custom commands change, this
schema must be updated in the same version bump.
"""

from __future__ import annotations

import asyncio
import logging
import re

from server.graph.state import ResumeState
from server.services.latex_utils import (
    check_brace_balance,
    check_environment_matching,
    check_placeholders,
    parse_custom_command_args,
    strip_latex_commands,
    _fix_unicode_chars,
)

_logger = logging.getLogger(__name__)

# Bound on N9r fix attempts before N9 falls back to plain-text section
# degradation. Mirrors n9r_fixer.py's docstring-implied max of 2.
MAX_FIX_ATTEMPTS = 2


class LatexDegradationError(Exception):
    """Raised when the assembled LaTeX is still invalid after N9r's fix
    attempts have been exhausted AND plain-text degradation of the
    implicated sections still fails full validation.

    Left uncaught here by design — it propagates out of the node and is
    caught by `_run_pipeline`'s existing `except Exception` handler in
    `server/api/generate.py`, which surfaces it as a `pipeline_error`.
    """

# ---------------------------------------------------------------------------
# CUSTOM COMMAND SCHEMA — mirrors definitions in template/master_resume.tex
#
# Each entry maps a LaTeX command to the exact number of arguments it expects.
# These are the ONLY commands Gemini is allowed to emit in its section output.
# Environment wrappers (\resumeSubHeadingListStart, \resumeItemListStart, etc.)
# stay in the locked template and are never generated by AI — they are not
# included here because N9 won't find them in section content slots.
# ---------------------------------------------------------------------------
CUSTOM_COMMAND_SCHEMA: dict[str, int] = {
    r"\resumeItem":           1,   # {bullet text}
    r"\resumeSubheading":     4,   # {company}{date}{role}{location}
    r"\resumeProjectHeading": 2,   # {title}{date} — confirmed exactly 2 args
                                    # per \newcommand{\resumeProjectHeading}[2]
                                    # in template/master_resume.tex.
}

# ---------------------------------------------------------------------------
# SECTION ANCHORS — used by map_errors_to_sections() to locate where each
# AI-generated content block landed in the fully-assembled latex_source.
#
# N8 (see server/graph/n8_assembler.py) substitutes AI-generated content into
# fixed slots via str.replace() on the locked template/master_resume.tex. By
# the time N9 runs, the %%PLACEHOLDER%% markers are already gone — but the
# \section{...} headers that immediately precede each slot are part of the
# locked template and are NEVER touched by AI, so they remain a stable,
# deterministic anchor for locating each block's line range in the final
# assembled document. EDUCATION marks the end of the AI-generated skills
# block (EDUCATION_BLOCK and CERTIFICATIONS_BLOCK are NOT AI-generated and
# are intentionally excluded from the mapped section names).
# ---------------------------------------------------------------------------
_SECTION_NAMES: tuple[str, ...] = ("summary", "experience", "projects", "skills")

_SECTION_ANCHOR_ORDER: tuple[str, ...] = (
    "summary", "experience", "projects", "skills", "__end__",
)

_SECTION_ANCHOR_PATTERNS: dict[str, str] = {
    "summary":    r"\\section\{PROFESSIONAL SUMMARY\}",
    "experience": r"\\section\{EXPERIENCE\}",
    "projects":   r"\\section\{PROJECTS\}",
    "skills":     r"\\section\{TECHNICAL SKILLS\}",
    "__end__":    r"\\section\{EDUCATION\}",
}

# Matches the "line {n}:" prefix produced by this module's check functions
# (e.g. "line 42: \resumeSubheading expected 4 args, got 3"). A single error
# string may contain multiple such references joined by "; "
# (see _check_custom_command_schema's "; ".join(errors[:5])).
_LINE_REF_RE = re.compile(r"line (\d+):")


def _locate_section_line_ranges(latex_source: str) -> dict[str, tuple[int, int]]:
    """Find the 1-indexed [start, end] line range of each AI-generated
    section's content block within the fully-assembled latex_source, by
    locating the fixed \\section{...} anchors that bound each slot.

    A section's range starts at its own \\section{...} header line and ends
    one line before the next-known anchor (or at the end of the document if
    no later anchor is found). Missing anchors simply omit that section from
    the returned mapping — callers must not assume all four keys are present.
    """
    lines = latex_source.split("\n")
    total_lines = len(lines)

    anchor_lines: dict[str, int] = {}
    for name in _SECTION_ANCHOR_ORDER:
        pattern = _SECTION_ANCHOR_PATTERNS[name]
        for idx, line in enumerate(lines, start=1):
            if re.search(pattern, line):
                anchor_lines[name] = idx
                break

    ranges: dict[str, tuple[int, int]] = {}
    for pos, name in enumerate(_SECTION_NAMES):
        start = anchor_lines.get(name)
        if start is None:
            continue
        end = total_lines
        for later_name in _SECTION_ANCHOR_ORDER[pos + 1:]:
            later_start = anchor_lines.get(later_name)
            if later_start is not None:
                end = later_start - 1
                break
        ranges[name] = (start, end)

    return ranges


def map_errors_to_sections(errors: list[str], latex_source: str) -> list[str]:
    """Maps validation error strings (which include line numbers) to the
    resume section (summary/experience/projects/skills) whose generated
    content block contains that line. Errors that fall outside any known
    section marker are treated as affecting the whole document and are NOT
    individually degradable — in that case degradation is skipped for those
    lines and the section list only contains sections that were concretely
    identified.

    Preconditions: `errors` follow the existing "line {n}: {message}" format
    produced by this module's check functions; entries may contain zero,
    one, or multiple "line {n}:" references (joined by "; ").

    Postconditions: returned list contains only values from
    {"summary", "experience", "projects", "skills"}, each appearing at most
    once, ordered by first occurrence across `errors` (and, within a single
    error string, by first occurrence of its embedded line references).
    """
    ranges = _locate_section_line_ranges(latex_source)

    result: list[str] = []
    for error in errors:
        for line_no_str in _LINE_REF_RE.findall(error):
            line_no = int(line_no_str)
            for section_name in _SECTION_NAMES:
                section_range = ranges.get(section_name)
                if section_range is None:
                    continue
                start, end = section_range
                if start <= line_no <= end:
                    if section_name not in result:
                        result.append(section_name)
                    break

    return result


async def _run_validation_checks(latex_source: str) -> list[str]:
    """Run all 5 validation checks concurrently and collect error messages.

    Extracted so both the initial validation pass and the post-degradation
    revalidation pass share the exact same check logic without duplicating
    the `asyncio.gather(...)` block.
    """
    results = await asyncio.gather(
        _check_brace_balance(latex_source),
        _check_environment_matching(latex_source),
        _check_placeholders(latex_source),
        _check_forbidden_chars(latex_source),
        _check_custom_command_schema(latex_source),
    )

    errors: list[str] = []
    for ok, msg in results:
        if not ok and msg:
            errors.append(msg)
    return errors


def _degrade_sections(latex_source: str, affected_sections: list[str]) -> str:
    """Replace the content of each named section with its plain-text
    equivalent (via `strip_latex_commands`), leaving every other line of
    `latex_source` — preamble, other sections, template structure —
    byte-identical.

    Uses the same line-range logic as `map_errors_to_sections` to locate
    each section's content boundaries.
    """
    ranges = _locate_section_line_ranges(latex_source)
    lines = latex_source.split("\n")

    # Replacing a slice with a single collapsed element can change the
    # length of `lines` (e.g. a 3-line section degrades to 1 element).
    # Ranges for every section were computed once against the *original*
    # line numbering, so applying replacements in ascending line order
    # would shift the indices of not-yet-processed sections. Applying them
    # in descending order of start line keeps every not-yet-processed
    # section's range valid, since a mutation only ever affects indices at
    # or after its own start position.
    ordered_sections = sorted(
        (name for name in affected_sections if ranges.get(name) is not None),
        key=lambda name: ranges[name][0],
        reverse=True,
    )

    for section_name in ordered_sections:
        start, end = ranges[section_name]
        # start/end are 1-indexed inclusive; convert to 0-indexed slice.
        section_lines = lines[start - 1:end]
        degraded_content = strip_latex_commands("\n".join(section_lines))
        lines[start - 1:end] = [degraded_content]

    return "\n".join(lines)


async def run(state: ResumeState) -> ResumeState:
    """Validate assembled LaTeX. Sets state.latex_valid and state.validation_errors.

    Pipeline:
    1. Run validation checks
    2. If errors found → attempt deterministic auto-fix (no LLM needed)
    3. Re-validate after auto-fix
    4. If still invalid and fix attempts remain → route to N9r (LLM fixer)
    5. If still invalid and fix attempts exhausted → degrade sections to
       plain text and revalidate once; raise LatexDegradationError if that
       also fails.
    """
    latex_source = state.get("latex_source", "")

    if not latex_source:
        return ResumeState(latex_valid=False, validation_errors=["No LaTeX source to validate"])

    errors = await _run_validation_checks(latex_source)

    if not errors:
        _logger.info("LaTeX validation passed")
        return ResumeState(latex_valid=True, validation_errors=[])

    _logger.warning("LaTeX validation found %d errors — attempting deterministic auto-fix", len(errors))

    # --- DETERMINISTIC AUTO-FIX (no LLM call) ---
    # Try to fix common issues programmatically before spending an LLM attempt.
    auto_fixed_source = _deterministic_auto_fix(latex_source, errors)

    if auto_fixed_source != latex_source:
        # Re-validate after auto-fix
        post_fix_errors = await _run_validation_checks(auto_fixed_source)
        if not post_fix_errors:
            _logger.info("LaTeX validation passed after deterministic auto-fix")
            return ResumeState(
                latex_source=auto_fixed_source,
                latex_valid=True,
                validation_errors=[],
            )
        # Auto-fix resolved some but not all errors
        _logger.info(
            "Deterministic auto-fix reduced errors from %d to %d",
            len(errors), len(post_fix_errors),
        )
        latex_source = auto_fixed_source
        errors = post_fix_errors

    # --- LLM FIX ROUTING ---
    fix_attempts = state.get("latex_fix_attempts", 0)
    if fix_attempts < MAX_FIX_ATTEMPTS:
        return ResumeState(
            latex_source=latex_source,
            latex_valid=False,
            validation_errors=errors,
        )

    # Fix attempts exhausted — attempt plain-text degradation of only the
    # sections implicated by the validation errors.
    affected_sections = map_errors_to_sections(errors, latex_source)

    if not affected_sections:
        # No degradable sections identified (e.g. document-level errors
        # with no line number, or lines outside all known section ranges).
        # Nothing would change by re-running validation, so skip straight
        # to the hard failure.
        raise LatexDegradationError(
            "LaTeX still invalid after " + str(MAX_FIX_ATTEMPTS) + " fix attempts, and no "
            "sections could be mapped to the validation errors for plain-text "
            "degradation: " + "; ".join(errors)
        )

    degraded_source = _degrade_sections(latex_source, affected_sections)
    final_errors = await _run_validation_checks(degraded_source)

    if not final_errors:
        _logger.warning(
            "LaTeX degraded to plain text for sections %s after exhausting fix attempts",
            affected_sections,
        )
        return ResumeState(
            latex_source=degraded_source,
            latex_valid=True,
            validation_errors=[],
            degraded_sections=affected_sections,
        )

    raise LatexDegradationError(
        "LaTeX still invalid after plain-text degradation of sections "
        f"{affected_sections}: " + "; ".join(final_errors)
    )


# ---------------------------------------------------------------------------
# Deterministic auto-fix: fixes common issues without needing an LLM call
# ---------------------------------------------------------------------------

def _deterministic_auto_fix(latex_source: str, errors: list[str]) -> str:
    """Apply rule-based fixes for common LaTeX errors.

    This runs BEFORE routing to N9r (LLM fixer) and handles:
    - Raw '&' outside tabular → \\&
    - Raw '%' in text → \\%
    - Raw '#' in text → \\#
    - Common brace issues in resumeItem/resumeSubheading
    - Unicode characters that pdflatex can't handle

    Returns the (possibly modified) LaTeX source.
    """
    from server.services.latex_utils import sanitize_latex_source, _fix_unicode_chars

    fixed = latex_source

    # 1. Fix forbidden characters (raw &, %, #)
    has_forbidden = any("Forbidden chars" in e for e in errors)
    if has_forbidden:
        fixed = _fix_forbidden_chars_deterministic(fixed)

    # 2. Fix unicode characters
    lines = fixed.split("\n")
    fixed = "\n".join(_fix_unicode_chars(line) for line in lines)

    # 3. Fix common brace issues in custom commands
    has_schema_errors = any("Command schema" in e for e in errors)
    if has_schema_errors:
        fixed = _fix_command_arg_issues(fixed)

    return fixed


def _fix_forbidden_chars_deterministic(latex: str) -> str:
    """Fix raw &, %, # characters outside safe contexts."""
    lines = latex.split("\n")
    result = []
    in_tabular = False
    tabular_depth = 0

    for line in lines:
        # Track tabular state
        if re.search(r"\\begin\{(tabular\*?|tabularx|longtable)\}", line):
            in_tabular = True
            tabular_depth += 1
        if re.search(r"\\end\{(tabular\*?|tabularx|longtable)\}", line):
            tabular_depth -= 1
            if tabular_depth <= 0:
                in_tabular = False
                tabular_depth = 0

        if in_tabular or r"\newcommand" in line or r"\renewcommand" in line:
            result.append(line)
            continue

        # Separate comment portion
        comment = ""
        # Find first unescaped % that's at brace depth 0
        comment_pos = _find_comment_start(line)
        if comment_pos is not None:
            comment = line[comment_pos:]
            line = line[:comment_pos]

        # Fix raw & → \&
        fixed = ""
        i = 0
        while i < len(line):
            if line[i] == "\\" and i + 1 < len(line) and line[i + 1] in "&%#$_":
                # Already escaped, skip both chars
                fixed += line[i:i+2]
                i += 2
            elif line[i] == "&":
                fixed += "\\&"
                i += 1
            elif line[i] == "#":
                # # is only valid in \newcommand definitions (already excluded above)
                fixed += "\\#"
                i += 1
            else:
                fixed += line[i]
                i += 1

        result.append(fixed + comment)

    return "\n".join(result)


def _find_comment_start(line: str) -> int | None:
    """Find the position of the first % that starts a LaTeX comment.

    A comment % must be:
    - Not escaped (not preceded by \\)
    - At brace depth 0 (not inside a command argument)
    """
    depth = 0
    i = 0
    while i < len(line):
        ch = line[i]
        if ch == "\\" and i + 1 < len(line):
            # Skip escaped character
            i += 2
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
        elif ch == "%" and depth == 0:
            return i
        i += 1
    return None


def _fix_command_arg_issues(latex: str) -> str:
    """Attempt to fix common argument count issues in custom commands.

    The most common issue is \\resumeProjectHeading with 1 or 3 args
    instead of exactly 2. This happens when Gemini merges or splits
    the title and date arguments.

    Strategy: find malformed commands and attempt to restructure their
    arguments to match the expected schema.
    """
    lines = latex.split("\n")
    result = []

    i = 0
    while i < len(lines):
        line = lines[i]

        # Fix \resumeProjectHeading with wrong arg count
        if "\\resumeProjectHeading" in line:
            # Collect the full command (may span multiple lines)
            cmd_lines, end_idx = _collect_command_lines(lines, i, "\\resumeProjectHeading", 2)
            if cmd_lines is not None:
                result.extend(cmd_lines)
                i = end_idx
                continue

        result.append(line)
        i += 1

    return "\n".join(result)


def _collect_command_lines(
    lines: list[str], start: int, cmd: str, expected_args: int
) -> tuple[list[str] | None, int]:
    """Try to collect and fix a command that may span multiple lines.

    Returns (fixed_lines, next_line_index) or (None, start+1) if no fix needed.
    """
    # For now, just pass through — the main fix is the forbidden chars
    # which is the error shown in the screenshot. More complex command
    # fixing can be added incrementally.
    return None, start + 1


# ---------------------------------------------------------------------------
# Individual check functions (each is an async coroutine for concurrency)
# ---------------------------------------------------------------------------

async def _check_brace_balance(latex: str) -> tuple[bool, str | None]:
    ok, msg = check_brace_balance(latex)
    return ok, ("Brace balance: " + msg) if not ok else None


async def _check_environment_matching(latex: str) -> tuple[bool, str | None]:
    ok, msg = check_environment_matching(latex)
    return ok, ("Environment matching: " + msg) if not ok else None


async def _check_placeholders(latex: str) -> tuple[bool, str | None]:
    ok, msg = check_placeholders(latex)
    return ok, ("Unsubstituted placeholder: " + msg) if not ok else None


async def _check_forbidden_chars(latex: str) -> tuple[bool, str | None]:
    """Check for unescaped special characters in text content.

    Raw '&' outside of \begin{tabular} environments and unescaped '%' not
    preceded by '\' are the most common LaTeX compilation killers.
    """
    # Remove comments first
    lines = latex.split("\n")
    errors: list[str] = []

    for i, line in enumerate(lines, start=1):
        stripped = line.split("%", 1)[0]  # remove LaTeX comments

        # Allow & inside tabular, tabular*, tabularx, longtable, etc.
        import re
        has_tabular = re.search(r"\\begin\{(tabular\*?|tabularx|longtable)\}", stripped) is not None
        has_newcommand = r"\newcommand" in stripped or r"\renewcommand" in stripped
        if "&" in stripped and not has_tabular and not has_newcommand:
            raw_amps = len(re.findall(r"(?<!\\)&", stripped))
            if raw_amps > 0:
                errors.append(f"line {i}: raw '&' outside tabular")

    if errors:
        return False, "Forbidden chars: " + "; ".join(errors[:3])
    return True, None


async def _check_custom_command_schema(latex: str) -> tuple[bool, str | None]:
    """Validate argument counts for all custom command calls against the schema."""
    command_names = tuple(CUSTOM_COMMAND_SCHEMA.keys())
    instances = parse_custom_command_args(latex, command_names)

    errors: list[str] = []
    for instance in instances:
        cmd = instance["command"]
        actual = instance["arg_count"]
        expected = CUSTOM_COMMAND_SCHEMA[cmd]

        if actual != expected:
            errors.append(
                f"line {instance['line']}: {cmd} expected {expected} args, got {actual}"
            )

    if errors:
        return False, "Command schema: " + "; ".join(errors[:5])
    return True, None
