"""N9 — LaTeX Validator (syntax + custom command schema validation).

Five parallel checks run against the assembled .tex file:
1. Brace balance (generic)
2. Environment matching (generic)
3. Placeholder check (generic)
4. Forbidden character check (generic)
5. Custom command schema validation (template-specific)

The CUSTOM_COMMAND_SCHEMA is hardcoded here — it must match the definitions
in template/master_resume.tex. If the template's custom commands change, this
schema must be updated in the same version bump.
"""

from __future__ import annotations

import asyncio
import logging

from server.graph.state import ResumeState
from server.services.latex_utils import (
    check_brace_balance,
    check_environment_matching,
    check_placeholders,
    parse_custom_command_args,
)

_logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# CUSTOM COMMAND SCHEMA — mirrors definitions in template/master_resume.tex
#
# Each entry maps a LaTeX command to the exact number of arguments it expects.
# These are the ONLY commands Gemini is allowed to emit in its section output.
# Environment wrappers (\resumeSubHeadingListStart, \resumeItemListStart, etc.)
# stay in the locked template and are never generated by AI — they are not
# included here because N9 won't find them in section content slots.
# ---------------------------------------------------------------------------
CUSTOM_COMMAND_SCHEMA: dict[str, int] = {
    r"\resumeItem":           1,   # {bullet text}
    r"\resumeSubheading":     4,   # {company}{date}{role}{location}
    # \resumeProjectHeading is variadic — accepts both 2-arg {title}{date}
    # and the Gemini-preferred 3-arg {\textbf{X}| \emph{Y}}{{stack}}{{date}}.
    # Disabled from schema validation to avoid false positives.
}


async def run(state: ResumeState) -> ResumeState:
    """Validate assembled LaTeX. Sets state.latex_valid and state.validation_errors.

    If valid → routes to N10 (pdf_compiler)
    If invalid → routes to N9r (latex_fixer)
    """
    latex_source = state.get("latex_source", "")

    if not latex_source:
        return ResumeState(latex_valid=False, validation_errors=["No LaTeX source to validate"])

    # Run all checks concurrently
    results = await asyncio.gather(
        _check_brace_balance(latex_source),
        _check_environment_matching(latex_source),
        _check_placeholders(latex_source),
        _check_forbidden_chars(latex_source),
        _check_custom_command_schema(latex_source),
    )

    errors: list[str] = []
    for ok, msg in results:
        if not ok and msg:
            errors.append(msg)

    if errors:
        _logger.warning("LaTeX validation failed: %d errors", len(errors))
        return ResumeState(latex_valid=False, validation_errors=errors)
    else:
        _logger.info("LaTeX validation passed")
        return ResumeState(latex_valid=True, validation_errors=[])


# ---------------------------------------------------------------------------
# Individual check functions (each is an async coroutine for concurrency)
# ---------------------------------------------------------------------------

async def _check_brace_balance(latex: str) -> tuple[bool, str | None]:
    ok, msg = check_brace_balance(latex)
    return ok, ("Brace balance: " + msg) if not ok else None


async def _check_environment_matching(latex: str) -> tuple[bool, str | None]:
    ok, msg = check_environment_matching(latex)
    return ok, ("Environment matching: " + msg) if not ok else None


async def _check_placeholders(latex: str) -> tuple[bool, str | None]:
    ok, msg = check_placeholders(latex)
    return ok, ("Unsubstituted placeholder: " + msg) if not ok else None


async def _check_forbidden_chars(latex: str) -> tuple[bool, str | None]:
    """Check for unescaped special characters in text content.

    Raw '&' outside of \begin{tabular} environments and unescaped '%' not
    preceded by '\' are the most common LaTeX compilation killers.
    """
    # Remove comments first
    lines = latex.split("\n")
    errors: list[str] = []

    for i, line in enumerate(lines, start=1):
        stripped = line.split("%", 1)[0]  # remove LaTeX comments

        # Allow & inside tabular, tabular*, tabularx, longtable, etc.
        import re
        has_tabular = re.search(r"\\begin\{(tabular\*?|tabularx|longtable)\}", stripped) is not None
        has_newcommand = r"\newcommand" in stripped or r"\renewcommand" in stripped
        if "&" in stripped and not has_tabular and not has_newcommand:
            raw_amps = len(re.findall(r"(?<!\\)&", stripped))
            if raw_amps > 0:
                errors.append(f"line {i}: raw '&' outside tabular")

    if errors:
        return False, "Forbidden chars: " + "; ".join(errors[:3])
    return True, None


async def _check_custom_command_schema(latex: str) -> tuple[bool, str | None]:
    """Validate argument counts for all custom command calls against the schema."""
    command_names = tuple(CUSTOM_COMMAND_SCHEMA.keys())
    instances = parse_custom_command_args(latex, command_names)

    errors: list[str] = []
    for instance in instances:
        cmd = instance["command"]
        actual = instance["arg_count"]
        expected = CUSTOM_COMMAND_SCHEMA[cmd]

        if actual != expected:
            errors.append(
                f"line {instance['line']}: {cmd} expected {expected} args, got {actual}"
            )

    if errors:
        return False, "Command schema: " + "; ".join(errors[:5])
    return True, None
