"""LangGraph state definition.

Single-source-of-truth for all fields passed between nodes. Uses TypedDict
with Annotated reducers for parallel-fan-in nodes that accumulate lists.
"""

from __future__ import annotations

import operator
from typing import Annotated, Any, TypedDict

from server.services.types import (
    JDProfile,
    KnowledgeGraph,
    SectionConfig,
    ScoredProject,
    SelectedProject,
)


class SectionOutputs(TypedDict, total=False):
    """Content generated by N7a–N7d."""

    summary: str  # plain text
    experience: str  # \resumeSubheading + \resumeItem calls
    projects: str  # \resumeProjectHeading + \resumeItem calls
    skills: str  # \textbf{}{} blocks


class ResumeState(TypedDict, total=False):
    """Complete LangGraph state. Every node reads/writes a subset.

    Fields with `Annotated[list, operator.add]` are used for fan-in
    nodes where parallel branches append to a shared accumulator.
    """

    # --- Session ---
    session_key: str
    session_id: str
    resume_from_node: str | None
    node_statuses: dict[str, str]  # node_id → pending|running|completed|failed

    # --- Input (N2 output) ---
    jd_raw: str
    jd_cleaned: str
    char_count: int
    estimated_tokens: int
    sections: list[SectionConfig]

    # --- JD Analysis (N3 output) ---
    jd_profile: JDProfile

    # --- Knowledge Graph (N4 output) ---
    kg_snapshot: KnowledgeGraph

    # --- Scoring & Selection (N5, N6 output) ---
    ranked_projects: list[ScoredProject]
    selected_projects: Annotated[list[SelectedProject], operator.add]
    selected_roles: list[dict[str, Any]]
    covered_skills: list[str]
    uncovered_skills: list[str]
    selected_skills_ordered: list[dict[str, Any]]

    # --- Generated Sections (N7a–N7d output, accumulated via fan-in) ---
    sections_output: Annotated[list[dict[str, Any]], operator.add]

    # --- LaTeX (N8, N9 output) ---
    latex_source: str
    latex_valid: bool
    validation_errors: list[str]
    latex_fix_attempts: int
    template_fallback: bool

    # --- PDF (N10 output) ---
    pdf_bytes: bytes

    # --- Response (N12 output) ---
    pdf_base64: str
    pdf_filename: str

    # --- Warnings ---
    warnings: Annotated[list[str], operator.add]
